### ISSUE TITLE
Invalid token

### ISSUE THREAD

**Issue by Aida-Enna** [castanhob/MognetPlugin#13]
It was working fine back on the 8th, but today I can't get the bot to post. The token generation seems to be broken, at least for me. I've tried remaking and removing then creating - The last 10 tokens haven't worked.

``21:44:26: Invalid token. Please check it or re-create it and try again.``

Anyone else having this issue? Bot has write permissions (it responded to the token commands in the channel).

**Comment by Leticro** [comment]
Yeah, I've been having the same issue. I feel like the issue started today with the latest release maybe.

**Comment by Leticro** [comment]
It started working again for me today, Maybe I just had to restart my computer or something, unsure what the trigger was.

**Comment by castanhob** [comment]
Interesting. @Aida-Enna , could you please confirm if it is still happening on your end?

**Comment by Aida-Enna** [comment]
Yep, fixed now. Thanks!
