### ISSUE TITLE
ACT update broke mognet

### ISSUE THREAD

**Issue by luisk2094** [castanhob/MognetPlugin#3]
![captura](https://user-images.githubusercontent.com/8525312/48984422-eddef880-f0c0-11e8-9b11-cd6db7a69d71.PNG)

**Comment by castanhob** [comment]
Hmm I wasnt tracking those errors properly. I'll take a look this weekend and make some updates on the plugin, tks for letting me know!

**Comment by Aida-Enna** [comment]
Further info - If you disable "Max Hit" (which is what the error throws), it doesn't show an error in the log. However, it also doesn't post to Discord.

**Comment by luisk2094** [comment]
yeah, i tried disabling a couple of things but nothing worked, so i guess its something on the code side with the new ACT update (it was really fast but i read something about changing some graphics with the max hit)

**Comment by lostsoulofawolf** [comment]
Is this still broken? I am having the same issue.

**Comment by Aida-Enna** [comment]
Yup.

**Comment by Aida-Enna** [comment]
@castanhob?

**Comment by castanhob** [comment]
We have the [0.2.0](https://github.com/castanhob/MognetPlugin/releases/tag/v0.2.0) release. Can you guys confirm if everything is working as intended?

**Comment by SadPopsicleBoy** [comment]
It is working as intended now!

**Comment by castanhob** [comment]
Great! Thanks for the feedback @SadPopsicleBoy !
