### ISSUE TITLE
Mognet fixed, needs release with new ACT.

### ISSUE THREAD

**Issue by Aida-Enna** [castanhob/MognetPlugin#5]
I finally opened the source and took a look around at Mognet - The issue in #3 and #4 is caused by the MognetPlugin.dll not being built with the most recent version of ACT. The API changed, breaking the plugin. Here's a prebuilt version until (if?) the author releases one on their page:

[MognetPlugin.zip](https://github.com/castanhob/MognetPlugin/files/2705876/MognetPlugin.zip)

Let me know if this doesn't fix the issue for anyone. Enjoy!

**Comment by castanhob** [comment]
@Aida-Enna , should be fixed after [0.2.0](https://github.com/castanhob/MognetPlugin/releases/tag/v0.2.0) release, can you confirm before I close the issue?

**Comment by Aida-Enna** [comment]
Yep, seems to be working fine! \ o / And no worries about the long time, stuff happens. It's all good! :3
